#!/bin/bash

python3 ./server.py &>/dev/null &
echo "Server started"

PID1=$!

sleep 5

python3 ./clients/c1.py &
PID2=$!

python3 ./clients/c2.py &
PID3=$!

python3 ./clients/c3.py &
PID4=$!

echo "Press q to exit and close server and clients"

while true; do
    read -n 1 key
    if [ $key = "q" ]; then
       kill $PID1 $PID2 $PID3 $PID4
       echo -e "\nServer and clients terminated."
       exit
    fi
done
